import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

import ReactQueryProvider from "@/provider/reactQueryProvider";
import "./globals.scss";
// import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${inter.className} ${geistMono.variable} antialiased`}
			>
				{/* <SessionProvider> */}
				<ReactQueryProvider>
					<Toaster />
					{children}
				</ReactQueryProvider>
				{/* </SessionProvider> */}
				<script
					async
					src="https://cdn.jsdelivr.net/gh/monsieurdd/mrD-SmoothScroller@latest/mrd-smoothscroller.js"
				></script>
			</body>
		</html>
	);
}
